const express = require('express');
const createCsvWriter = require('csv-writer').createObjectCsvWriter;
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const Vehicle = require('../models/Vehicle');
const { authenticateToken, authorizeAdmin } = require('../middleware/auth');

const router = express.Router();

// Apply authentication to all export routes
router.use(authenticateToken);

// GET /api/exports/vehicles/csv - Export vehicles as CSV
router.get('/vehicles/csv', authorizeAdmin, async (req, res) => {
  try {
    const vehicles = await Vehicle.findAll(1000, 0); // Get all vehicles for export

    if (vehicles.length === 0) {
      return res.status(404).json({ error: 'No vehicles found to export' });
    }

    // Create CSV writer
    const csvWriter = createCsvWriter({
      path: 'temp_vehicles.csv',
      header: [
        { id: 'id', title: 'ID' },
        { id: 'vehicle_type', title: 'Vehicle Type' },
        { id: 'vehicle_number', title: 'Vehicle Number' },
        { id: 'model', title: 'Model' },
        { id: 'color', title: 'Color' },
        { id: 'is_ev', title: 'EV Vehicle' },
        { id: 'owner_name', title: 'Owner Name' },
        { id: 'email', title: 'Email' },
        { id: 'employee_student_id', title: 'Employee/Student ID' },
        { id: 'created_at', title: 'Registration Date' }
      ]
    });

    // Write CSV file
    await csvWriter.writeRecords(vehicles);

    // Set headers for file download
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', 'attachment; filename="vehicles_export.csv"');

    // Stream file to response
    const fileStream = fs.createReadStream('temp_vehicles.csv');
    fileStream.pipe(res);

    // Clean up temp file after streaming
    fileStream.on('end', () => {
      fs.unlinkSync('temp_vehicles.csv');
    });

  } catch (error) {
    console.error('CSV export error:', error);
    res.status(500).json({ error: 'Failed to export CSV' });
  }
});

// GET /api/exports/vehicles/pdf - Export vehicles as PDF
router.get('/vehicles/pdf', authorizeAdmin, async (req, res) => {
  try {
    const vehicles = await Vehicle.findAll(1000, 0); // Get all vehicles for export

    if (vehicles.length === 0) {
      return res.status(404).json({ error: 'No vehicles found to export' });
    }

    // Create PDF document
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const filename = 'vehicles_export.pdf';

    // Set headers for file download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    // Pipe PDF to response
    doc.pipe(res);

    // PDF Header
    doc.fontSize(20).text('VNR Parking Pilot - Vehicle Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(2);

    // Table headers
    const tableTop = 150;
    const colWidths = [50, 80, 80, 80, 50, 80, 100, 80];
    let currentY = tableTop;

    // Draw table header
    doc.font('Helvetica-Bold');
    doc.rect(50, currentY - 5, 500, 25).fill('#f0f0f0').stroke();
    doc.fillColor('black').fontSize(10);

    let xPos = 50;
    const headers = ['ID', 'Type', 'Number', 'Model', 'Color', 'EV', 'Owner', 'Email'];
    headers.forEach((header, i) => {
      doc.text(header, xPos + 5, currentY + 5, { width: colWidths[i], align: 'left' });
      xPos += colWidths[i];
    });

    currentY += 25;

    // Draw table rows
    doc.font('Helvetica');
    vehicles.forEach((vehicle, index) => {
      // Alternate row colors
      if (index % 2 === 0) {
        doc.rect(50, currentY - 5, 500, 20).fill('#f9f9f9').stroke();
      }

      xPos = 50;
      const rowData = [
        vehicle.id.toString(),
        vehicle.vehicle_type.toUpperCase(),
        vehicle.vehicle_number,
        vehicle.model || 'N/A',
        vehicle.color || 'N/A',
        vehicle.is_ev ? 'Yes' : 'No',
        vehicle.owner_name,
        vehicle.email
      ];

      rowData.forEach((data, i) => {
        doc.fillColor('black').text(data, xPos + 5, currentY + 2, { width: colWidths[i], align: 'left' });
        xPos += colWidths[i];
      });

      currentY += 20;

      // Add new page if needed
      if (currentY > 700) {
        doc.addPage();
        currentY = 50;
      }
    });

    // Summary section
    doc.moveDown(2);
    doc.font('Helvetica-Bold').fontSize(12);
    doc.text(`Total Vehicles: ${vehicles.length}`, 50, currentY);
    doc.text(`EV Vehicles: ${vehicles.filter(v => v.is_ev).length}`, 200, currentY);
    doc.text(`Regular Vehicles: ${vehicles.filter(v => !v.is_ev).length}`, 350, currentY);

    // Footer
    doc.fontSize(8).fillColor('gray');
    doc.text('Generated by VNR Parking Pilot System', 50, doc.page.height - 50, { align: 'center' });

    // Finalize PDF
    doc.end();

  } catch (error) {
    console.error('PDF export error:', error);
    res.status(500).json({ error: 'Failed to export PDF' });
  }
});

// GET /api/exports/stats - Get export statistics
router.get('/stats', authorizeAdmin, async (req, res) => {
  try {
    const stats = await Vehicle.getStats();

    res.json({
      totalVehicles: stats.total_vehicles,
      evVehicles: stats.total_ev,
      carVehicles: stats.total_cars,
      bikeVehicles: stats.total_bikes,
      exportDate: new Date().toISOString()
    });
  } catch (error) {
    console.error('Export stats error:', error);
    res.status(500).json({ error: 'Failed to get export statistics' });
  }
});

module.exports = router;
